---
- name: download terraform
  get_url: url={{ terraform_base_url }}/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip dest=/home/{{ ansible_ssh_user }}/terraform.zip

- name: extract terraform
  sudo: yes
  unarchive: src=/home/{{ ansible_ssh_user }}/terraform.zip dest=/usr/local/bin copy=no
  # Ansible 2.0 would let us do this in one step.

- name: clean up zip
  file: path=/home/{{ ansible_ssh_user }}/terraform.zip state=absent
